---
title: "College Basketball Summary Statistics"
author: "Blake Khaleghi, Neel Shastri, Grant Sielman, Ryan King"
output: html_document
date: "2022-11-13"
---


```{r setup, include=FALSE}

# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')


```


```{r setup-2}

# Always print this out before your assignment
sessionInfo()
getwd()

```


<!-- ### start answering your problem set here -->
<!-- You may export your homework in either html or pdf, with the former usually being easier. 
     To export or compile your Rmd file: click above on 'Knit' then 'Knit to HTML' -->
<!-- Be sure to submit both your .Rmd file and the compiled .html or .pdf file for full credit -->


```{r setup-3}

# load all your libraries in this chunk 
library('tidyverse')
library('rsample')
library('glmnet')
library('glmnetUtils')
library('forcats')
library('randomForest')
library('ISLR')
library('dplyr')
library('ggplot2')
library('partykit')
library('PerformanceAnalytics')
library('rpart')       
library('rpart.plot')  

# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 

```



```{r}

CBB_data <- read_csv("CBB_cleaned.csv")

CBB_variables <- CBB_data %>% select(W, ADJOE, ADJDE, EFG_O, EFG_D, TOR, TORD, FTR, FTRD, TEAM, YR)

glimpse(CBB_variables)


```


```{r}

is.character(CBB_variables$TEAM)

```


```{r}


CBB_variables <- CBB_variables %>% mutate(TEAM = as_factor(TEAM))

class(CBB_variables$TEAM)

```


```{r}

levels(CBB_variables$TEAM)

```


```{r}

library('forcats')

CBB_variables <- CBB_variables %>% mutate(TEAM_simple = fct_lump_n(TEAM, n = 1))

```


```{r}

levels(CBB_variables$TEAM_simple)

```



```{r}

CBB_variables %>% group_by(TEAM_simple)

```

```{r}

library('vtable')
sumtable(CBB_variables)

```

RIDGE MODEL

```{r}
library('psych')

CBB_split <- initial_split(CBB_variables, prop = .75)
CBB_train <- training(CBB_split)
CBB_test <- testing(CBB_split)

CBB_ridge <- cv.glmnet(W ~ ADJOE + ADJDE + EFG_O + EFG_D + TOR + TORD + FTR + FTRD + TEAM + YR,
                       data = CBB_train,
                       # note alpha = 0 sets ridge!  
                       alpha = 0)

print(CBB_ridge$lambda.min)
print(CBB_ridge$lambda.1se)
 
plot(CBB_ridge)

coef(CBB_ridge, s = CBB_ridge$lambda.min) %>% round(3)
coef(CBB_ridge, s = CBB_ridge$lambda.1se) %>% round(3)

CBB_ridge_coefs <- tibble(
  `varnames` = rownames(coef(CBB_ridge, s = CBB_ridge$lambda.1se)),
  `ridge_min` = coef(CBB_ridge, s = CBB_ridge$lambda.min) %>% 
    round(3) %>% as.matrix() %>% as.data.frame(),
    `ridge_1se` = coef(CBB_ridge, s = CBB_ridge$lambda.1se) %>% 
    round(3) %>% as.matrix() %>% as.data.frame()
)

summary(CBB_ridge_coefs)

describe(CBB_ridge_coefs)

```


```{r}
mod2 <- lm(W ~ ADJOE + ADJDE + EFG_O + EFG_D + TOR + TORD + FTR + FTRD + factor(TEAM) + YR, data = CBB_train)
summary(mod2)
```


```{r}
library('sjPlot')
tab_model(mod2)
```


```{r}
tidy(mod2)
```

```{r}
library('ggplot2')
mod3 <- lm(W ~ ADJOE + ADJDE, data = CBB_train) 
summary(mod3)
```


```{r}
levels(droplevels(CBB_variables$TEAM))
```



```{r}
library(ggplot2)
ggplot(CBB_train, aes(x = predict(mod2), y = CBB_train$W)) +
geom_point() +
geom_abline(intercept = 0, slope = 1) +
labs(x = 'Predicted Values', y = 'Actual Values', title = 'Predicted vs Actual Values' )
```

REGRESSION TREE

```{r}
library(partykit)
library(tidyverse)
library(PerformanceAnalytics)
library(rpart)       
library(rpart.plot)  
CBB_data <- read_csv("CBB_cleaned.csv")
CBB_variables <- CBB_data %>% select(WINPER, ADJOE, ADJDE, EFG_O, EFG_D, TOR, TORD, FTR, FTRD, TEAM, YR, ORB, DRB)

CBB_Defense_Tree <- ctree(WINPER ~ ADJDE + EFG_D + TORD + FTRD + DRB,
                      data = CBB_variables,
                      control = partykit::ctree_control(alpha= 0.1,
                                                        minbucket = 130))

CBB_Defense_Tree
plot(CBB_Defense_Tree)
CBB_Offense <- ctree(WINPER ~ ADJOE + EFG_O + TOR + FTR + ORB,
                     data = CBB_variables,
                     control = partykit::ctree_control(alpha= 0.1,
                                                        minbucket = 130))
CBB_Offense
plot(CBB_Offense)
library('rpart')
CBB_Defense_Tree_Rpart <- rpart(WINPER ~ ADJDE + EFG_D + TORD + FTRD + DRB,
                      data = CBB_variables,
                      method = "class", control = list(cp = 0,
                                                       minsplit = 10,                                             maxdepth = 10))
CBB_Defense_Tree_Rpart$cptable
printcp(CBB_Defense_Tree_Rpart)
CBB_Offense_Tree_Rpart <- rpart(WINPER ~ ADJOE + EFG_O + TOR + FTR + ORB,
                      data = CBB_variables,
                      method = "class", control = list(cp = 0,
                                                       minsplit = 10,                                             maxdepth = 10))
CBB_Offense_Tree_Rpart$cptable
printcp(CBB_Offense_Tree_Rpart)
```

Logistic Regression

```{r}
CBB_data_other <- read_csv("CBB_cleaned.csv")

mod1 <- glm(WINPER ~ ADJOE + ADJDE + EFG_O + EFG_D + TOR + 
              TORD + FTR + FTRD, family = quasibinomial, data = CBB_data)
summary(mod1)
ggplot(CBB_data_data, aes(x = WINPER, y = EFG_O, color = W)) + geom_point() + facet_wrap(~CONF_Other) +
  theme_minimal() + 
  labs(x = "Team Win %", y = "Team Adjusted Offensive Efficiency")

```


MESS AROUND BELOW 


```{r}


mod1 <- glm(WINPER ~ ADJOE + ADJDE + EFG_O + EFG_D + TOR + 
              TORD + FTR + FTRD, family = quasibinomial, data = CBB_data)


ggplot(CBB_data, aes(x = WINPER, y = EFG_O, color = W)) + geom_point() + facet_wrap(~YR) + theme_minimal() + labs(x = "Team Win %", y = "Team Adjusted Offensive Efficiency")


```







